const games=[
{id:"madan",title:"魔弾ダンダンジョン",category:"就職作品 / 現在制作中",members:"制作人数：1人",period:"",image:"images/madan.svg",gif:"",description:"ローグライク要素を持つアクションシューティング",role:"個人制作",youtube:"",pdf:""},
{id:"mogura",title:"モグラ相撲",category:"2年生 / チーム制作",members:"制作人数：4人",period:"制作期間：10日",image:"images/mogura.svg",gif:"",description:"敵AIと落とし合う、ターン性ひっぱりアクション",role:"",youtube:"https://youtu.be/zrvy-mwzmvk",pdf:""},
{id:"karasu",title:"急降下カラス飛行",category:"2年生 / チーム制作",members:"制作人数：3人",period:"制作期間：1ヶ月",image:"images/karasu.svg",gif:"",description:"「急降下」で攻撃する自動移動2Dアクション",role:"",youtube:"https://youtu.be/xlVGWxQMN6c",pdf:""},
{id:"bunbun",title:"ブンブンている",category:"2年生 / チーム制作",members:"制作人数：4人",period:"制作期間：1ヶ月",image:"images/bunbun.svg",gif:"",description:"尻尾で攻撃する見下ろし視点ボス戦アクション",role:"",youtube:"https://youtu.be/id5O8JI2rwc",pdf:""},
{id:"soutai",title:"相対傘",category:"2年生 / チーム制作",members:"制作人数：3人",period:"制作期間：1ヶ月",image:"images/soutai.svg",gif:"",description:"歌舞伎風のボス戦アクション",role:"",youtube:"https://youtu.be/oC-jBzdE3Kk",pdf:""},
{id:"saiguy",title:"災Guy",category:"3年生 / チーム制作",members:"制作人数：3人",period:"制作期間：4ヶ月",image:"images/saiguy.svg",gif:"",description:"ブロック破壊が爽快な落下アクション",role:"",youtube:"https://youtu.be/YpGYRxa5FFo",pdf:""},
{id:"wataru",title:"わたる",category:"3年生 / チーム制作",members:"制作人数：3人",period:"制作期間：10日",image:"images/wataru.svg",gif:"",description:"風を操り綿毛をゴールさせる2Dアクション",role:"",youtube:"",pdf:""},
{id:"chameleon",title:"カメレオンブロック",category:"1年生 / チーム制作",members:"チーム制作",period:"",image:"images/chameleon.svg",gif:"",description:"",role:"",youtube:"https://youtu.be/hnraIZnrIc4",pdf:""},
{id:"utsuro",title:"うつろなカタチ",category:"1年生 / チーム制作",members:"チーム制作",period:"",image:"images/utsuro.svg",gif:"",description:"",role:"",youtube:"https://youtu.be/Oe-dwgPQEFk",pdf:""},
{id:"smogrin",title:"スモグリン",category:"1年生 / チーム制作",members:"チーム制作",period:"",image:"images/smogrin.svg",gif:"",description:"",role:"",youtube:"https://youtu.be/EC734TCm67M",pdf:""},
{id:"ishizuna",title:"石絆",category:"1年生 / 個人制作",members:"個人制作",period:"",image:"images/ishizuna.svg",gif:"",description:"",role:"",youtube:"https://youtu.be/qn9yS41fRxM",pdf:""},
{id:"fruitsshooter",title:"FruitsShooter",category:"1年生 / 個人制作",members:"個人制作",period:"",image:"images/fruitsshooter.svg",gif:"",description:"",role:"",youtube:"https://youtu.be/CJxDBQTC9u8",pdf:""}
];
const $=id=>document.getElementById(id);
function createCard(g,featured=false){const c=document.createElement("article");c.className=featured?"featured-card":"game-card";c.innerHTML=`<img class="game-thumb" src="${g.image}" alt="${g.title}"><div class="game-card-body"><p class="game-category">${g.category}</p><h3>${g.title}</h3></div>`;c.onclick=()=>openModal(g);return c}
function render(){document.getElementById("featuredWork").appendChild(createCard(games[0],true));const groups={secondYearTeam:["mogura","karasu","bunbun","soutai"],thirdYearTeam:["saiguy","wataru"],firstYearTeam:["chameleon","utsuro","smogrin"],firstYearPersonal:["ishizuna","fruitsshooter"]};for(const [id,ids] of Object.entries(groups)){ids.forEach(x=>document.getElementById(id).appendChild(createCard(games.find(g=>g.id===x))))}}
function addLink(box,label,url){if(!url)return;const a=document.createElement("a");a.className="modal-link";a.href=url;a.target="_blank";a.rel="noopener noreferrer";a.textContent=label;box.appendChild(a)}
function openModal(g){document.getElementById("modalImage").src=g.gif||g.image;document.getElementById("modalImage").alt=g.title;document.getElementById("modalCategory").textContent=g.category;document.getElementById("modalTitle").textContent=g.title;document.getElementById("modalMembers").textContent=g.members;document.getElementById("modalPeriod").textContent=g.period;document.getElementById("modalDescription").textContent=g.description;document.getElementById("modalRole").textContent=g.role?"担当・制作形態："+g.role:"";const box=document.getElementById("modalLinks");box.innerHTML="";addLink(box,"▶ 紹介動画を見る",g.youtube);addLink(box,"📄 プログラム説明資料を見る",g.pdf);document.getElementById("modal").classList.add("is-open");document.body.style.overflow="hidden"}
function closeModal(){document.getElementById("modal").classList.remove("is-open");document.body.style.overflow=""}
document.getElementById("modalClose").onclick=closeModal;document.getElementById("modalOverlay").onclick=closeModal;document.addEventListener("keydown",e=>{if(e.key==="Escape")closeModal()});render();